% % type: function
% describtion: Groups the checkboxes into a one List
% =========================================================================
function List = grouping(handles,Listname)
switch Listname
    case 'checkbox'
        List = [handles.checkbox1 handles.checkbox2 handles.checkbox3...
            handles.checkbox4 handles.checkbox5 handles.checkbox6...
            handles.checkbox7 handles.checkbox8 handles.checkbox9...
            handles.checkbox10 handles.checkbox11 handles.checkbox12...
            handles.checkbox13 handles.checkbox14 handles.checkbox15...
            handles.checkbox16 handles.checkbox17 handles.checkbox18 handles.checkbox19...
            handles.checkbox20 handles.checkbox21 handles.checkbox22...
            handles.checkbox23 handles.checkbox24 handles.checkbox25...
            handles.checkbox26 handles.checkbox27 handles.checkbox28 handles.checkbox29...
            handles.checkbox30 handles.checkbox31 handles.checkbox32...
            handles.checkbox33 handles.checkbox34 handles.checkbox35...
            handles.checkbox36 handles.checkbox37 handles.checkbox38...
            handles.checkbox39 handles.checkbox40 handles.checkbox41...
            handles.checkbox42 handles.checkbox43 handles.checkbox44...
            handles.checkbox45 handles.checkbox46 handles.checkbox47...
            handles.checkbox48 handles.checkbox49 handles.checkbox50];
    case 'button'
        List = [handles.Load_Fluence handles.Load_Fluence_SD handles.Load_Fluence_Cor...
            handles.Load_Activity handles.Load_Activity_SD handles.Load_Activity_Cor...
            handles.Norm];
    case 'radiobutton'
        List = [handles.radiobutton1 handles.radiobutton2 handles.radiobutton3...
            handles.radiobutton4 handles.radiobutton5 handles.radiobutton6...
            handles.radiobutton7 handles.radiobutton8 handles.radiobutton9...
            handles.radiobutton10 handles.radiobutton11 handles.radiobutton12...
            handles.radiobutton13 handles.radiobutton14 handles.radiobutton15...
            handles.radiobutton16 handles.radiobutton17 handles.radiobutton18 handles.radiobutton19...
            handles.radiobutton20 handles.radiobutton21 handles.radiobutton22...
            handles.radiobutton23 handles.radiobutton24 handles.radiobutton25...
            handles.radiobutton26 handles.radiobutton27 handles.radiobutton28 handles.radiobutton29...
            handles.radiobutton30 handles.radiobutton31 handles.radiobutton32...
            handles.radiobutton33 handles.radiobutton34 handles.radiobutton35...
            handles.radiobutton36 handles.radiobutton37 handles.radiobutton38...
            handles.radiobutton39 handles.radiobutton40 handles.radiobutton41...
            handles.radiobutton42 handles.radiobutton43 handles.radiobutton44...
            handles.radiobutton45 handles.radiobutton46 handles.radiobutton47...
            handles.radiobutton48 handles.radiobutton49 handles.radiobutton50];
end
% =========================================================================